### ISSUE TITLE
published crates don't contain license texts but only contain bogus symlink

### ISSUE THREAD

**Issue by decathorpe** [Seeker14491/opener#16]
It looks like the symlinks that were added in order to include license files in published crates don't work correctly.
I downloaded sources for opener v0.5.0 and v0.5.1 from crates.io, and in both cases the files are bogus - `LICENSE-APACHE` is a file that contains the string `../LICENSE-APACHE`, etc.

If you are running "cargo publish" on Windows, I think symlinks do not work for this purpose, and as far as I know, adding full copies of these files is the only way to work around the fact that symlinks don't really work on Windows. :(

**Comment by Seeker14491** [comment]
I publish on Linux so I don't know how it happened, but indeed the symlinks were borked on my local version of the repo. I recreated them to fix them, and published v0.5.2 with this issue fixed.

**Comment by decathorpe** [comment]
Wow, that's strange. Either way, I can confirm that 0.5.2 fixes the problem, so thanks a lot for the quick fix! 🎉
