### ISSUE TITLE
Reveal file in file explorer

### ISSUE THREAD

**Issue by bash** [Seeker14491/opener#17]
Hi, I'm using this library in my [rusty GUI for magic-wormhole](https://github.com/bash/portal).

One feature that I was missing is a function that opens the file explorer and reveals the file in its containing folder instead of opening it. On Windows and macOS this is [fairly easy](https://github.com/bash/portal/blob/2632b0272646ad535c82c687fa553aad9d9aa26e/src/shell/reveal.rs) to do. I'm not sure how easy this is on other systems.

I would love to to contribute a PR if you think that this is in scope for this crate.

**Comment by Seeker14491** [comment]
I think this functionality would be great! We'd need to support Linux too though. [I read that](https://askubuntu.com/a/1424380/916023) Electron implements this in Linux by using D-Bus, but it falls back to calling xdg-open with the parent directory if it fails. I think we could do something similar: try using D-Bus, and if it fails, fall back to calling our `opener::open()` function with the parent folder of the file we meant to reveal.
