### ISSUE TITLE
URL opened as file path in WSL2

### ISSUE THREAD

**Issue by btwiuse** [Seeker14491/opener#20]
I use `open_browser` to open the `http://127.0.0.1:33541` in WSL2 with `BROWSER="/mnt/c/Program Files/Firefox Nightly/firefox.exe"`

The browser opens `file://///wsl.localhost/Arch/home/aaron/gear/http/127.0.0.133541` instead of `http://127.0.0.1:33541`.

Such behavior is caused by wslpath:

```
$ wslpath -w '127.0.0.1:33541'
http\127.0.0.133541
```

Can we check if the opened path is a url first before passing it to `wslpath`?

**Comment by Seeker14491** [comment]
I just fixed this 3 days ago (474f93b75ca3ea6a3c50fe7c9dbe293fd0a18d40). I plan on releasing a new version very soon.

**Comment by btwiuse** [comment]
But the current solution is relying on the presence of `wslview`, which is unavailable on non-ubuntu distros. (I use arch btw)

**Comment by Seeker14491** [comment]
It's [available for installation](https://wslutiliti.es/wslu/install.html) on other distros including Arch (which is also my WSL distro), but it's not preinstalled. I *did* just find out it's no longer preinstalled on Ubuntu as of 22.04. If `wslview` is missing, there is fallback to `xdg-open`, though that might not do the "right" thing.

**Comment by Seeker14491** [comment]
I opened #21 for the issue of requiring either `wslview` or `xdg-open` to be available on WSL.
