### ISSUE TITLE
Arc Browser not opening.

### ISSUE THREAD

**Issue by V0idLord** [Seeker14491/opener#33]
I have an issue with opening `rustup doc --book` with the Arc Browser, I get no errors, but the browser just doesn't open. I opened a issue on Rust with the link bellow, but they directed me here. Any idea why this happens? setting edge as default browser solves the issue, but I usually use Arc for everything. Thanks and sorry if the problem is not on your end.
![image](https://github.com/user-attachments/assets/b71e45a3-9be2-49b8-9dcd-97de1a7c9732)

https://github.com/rust-lang/rustup/issues/3992#issue-2469095999

**Comment by Seeker14491** [comment]
Are you on native Windows or WSL?

**Comment by V0idLord** [comment]
Native Windows

**Comment by V0idLord** [comment]
> Are you on native Windows or WSL?

Native Windows

**Comment by Seeker14491** [comment]
It's an Arc Browser bug:

https://www.reddit.com/r/ArcBrowser/comments/1c16ls9/i_set_arc_browser_as_my_windows_default_browser/
https://www.reddit.com/r/ArcBrowser/comments/1f4jjxw/arc_doesnt_respond_to_shell_or_console_commands/

On Windows we're just using the standard `ShellExecuteW()` Windows API function, but Arc Browser isn't responding to it for some reason.
