### ISSUE TITLE
On macOS, `opener` uses Safari where as the `open` command uses Firefox

### ISSUE THREAD

**Issue by djc** [Seeker14491/opener#5]
When running code from `cargo run` in VS Code, the `opener::open()` call when provided with a URL will open that URL in Safari. If I run `open` from the command line in the same shell, it opens in Firefox.

**Comment by Seeker14491** [comment]
That's strange. On mac all this library does to open a path just boils down to this:

```rust
Command::new("open")
    .arg(path_you_provide)
    .stdin(Stdio::null())
    .stdout(Stdio::null())
    .stderr(Stdio::piped())
    .spawn()?;
```

Therefore I don't see how this issue could be caused by this library. You should experience the same behavior manually running the `open` command like this in your code.

**Comment by djc** [comment]
Can't reproduce this now, anyway. Sorry for the noise!
